# This is a basic workflow that is manually triggered

name: Test

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "Hello $GITHUB_ENV"
        echo "CUSTOM_BRANCH=$(echo "${GITHUB_REF##*/}")" >> $GITHUB_ENV
        echo "BUILD_SHA=$(echo "$(git rev-parse --short "$GITHUB_SHA")")" >> $GITHUB_ENV
        echo $GITHUB_ENV
