# This is a basic workflow that is manually triggered

name: Test

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "GITHUB_CUSTOM_BRANCH=$(echo "${GITHUB_REF##*/}$(date +'-%d-%m-%Y-%H:%M:%S')")" >> $GITHUB_ENV
    - run: |
        echo "${GITHUB_CUSTOM_BRANCH}"
    - run: |
        echo "${GITHUB_REF}"
    - run: |
        echo "${GITHUB_HEAD_REF}"
