name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${GITHUB_SHA::7}
    steps:
     - name: first step
       run: |
         echo ${GITHUB_SHA}
         echo $SHA
          
